name: Fetch statistics of downloading count

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch
        run: TOKEN=${{ secrets.GITHUB_TOKEN }} ./fetch-statistics.py > "statistics/$(date --iso-8601).json"
      - name: Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add statistics
          git commit -m "Add statistics on $(date --iso-8601)"
          git push
      
